// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantRaterAPI.Data;

#nullable disable

namespace RestaurantRaterAPI.Migrations
{
    [DbContext(typeof(RestaurantDbContext))]
    [Migration("20231220231315_BowsersChiliAndRating")]
    partial class BowsersChiliAndRating
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestaurantRaterAPI.Data.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CleanlinessScore")
                        .HasColumnType("float");

                    b.Property<double>("EnvironmentScore")
                        .HasColumnType("float");

                    b.Property<double>("FoodScore")
                        .HasColumnType("float");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CleanlinessScore = 10.0,
                            EnvironmentScore = 8.8000000000000007,
                            FoodScore = 7.5,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 2,
                            CleanlinessScore = 9.9000000000000004,
                            EnvironmentScore = 9.8000000000000007,
                            FoodScore = 8.5,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 3,
                            CleanlinessScore = 10.0,
                            EnvironmentScore = 5.7999999999999998,
                            FoodScore = 3.5,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 4,
                            CleanlinessScore = 7.0,
                            EnvironmentScore = 6.7999999999999998,
                            FoodScore = 6.5,
                            RestaurantId = 2
                        });
                });

            modelBuilder.Entity("RestaurantRaterAPI.Data.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "1Up Lane",
                            Name = "Super Mario Pasta Cavern"
                        },
                        new
                        {
                            Id = 2,
                            Address = "123 GRRR CT",
                            Name = "Bowsers Hot Chili Shop"
                        });
                });

            modelBuilder.Entity("RestaurantRaterAPI.Data.Rating", b =>
                {
                    b.HasOne("RestaurantRaterAPI.Data.Restaurant", "Restaurant")
                        .WithMany("Ratings")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("RestaurantRaterAPI.Data.Restaurant", b =>
                {
                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
